version: "3.8"
services:
  mysql2:
    image: mysql:5.7.21
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: "spring"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - 3306:3306
  keycloak: #http://localhost:8080/auth, http://localhost:8080/auth/realms/appsdeveloperblog/account/
    image: quay.io/keycloak/keycloak:11.0.2
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    ports:
      - 8080:8080