spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: root
    initialization-mode: always

server:
  port: 8081

logging:
  level:
    org:
      springframework: TRACE