server:
  port: 9090
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
    client:
      client-id: resourceserver
      client-secret: resourceserversecret
